cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'roundup'
brew 'spark'
brew 'unrar'

# cask '1password'
# cask 'adium'
# cask 'atom'
# cask 'firefox'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'slack'
# cask 'steam'
# cask 'transmission'
# cask 'vlc'
