#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

set -x
# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# This should really be in vim/install.sh, but I couldn't figure out how to make it run inside another script
echo "> vim +BundleInstall!"
SHELL=$(which sh) vim +BundleInstall! +BundleClean! +qall
